---
# File: main.yml - Handlers for Consul

- name: restart consul
  include: restart_consul.yml
  tags: begin_running

- name: start consul
  include: start_consul.yml
  tags: begin_running

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: start dnsmasq
  service:
    name: dnsmasq
    enabled: yes
    state: started
