---
- name: restart consul on linux
  service:
    name: consul
    state: restarted
  when: ansible_os_family != "Windows"

- name: restart consul on windows
  win_nssm:
    name: consul
    state: restarted
    application: "{{ consul_binary }}"
    app_parameters_free_form: "agent -config-file='{{ consul_config_path }}/config.json' -config-dir='{{ consul_configd_path }}'"
    stdout_file: "{{ consul_log_path }}/consul-nssm-output.log"
    stderr_file: "{{ consul_log_path }}/consul-nssm-error.log"
  when: ansible_os_family == "Windows"
